name: Ubuntu - Server

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: ubuntu-latest
    timeout-minutes: 9999

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          sudo apt update
          sudo apt install -y openssh-server
          sudo systemctl enable ssh
          sudo systemctl start ssh
          echo "SSH setup complete!"

      - name: Show IP Address
        run: |
          # Get the IP address of the server
          ip_address=$(hostname -I | awk '{print $1}')
          echo "Server IP Address: $ip_address"
